carta/.github

.github/workflows/type_annotation.yml

Tee doesn't pass the exit code. `mypy . | tee mypy_report.txt`
`set -o pipefail` will enable the pipe command to fail when some of the command fail.

CWS-938 fail the job when Mypy fails

---

.github/workflows/type_annotation.yml

Create a venv for installing dependencies and cache it to speed it up.
The first run creates the cache:
https://github.com/carta/automated-refactoring/runs/5221039631?check_suite_focus=true
The second run reuses the cache and saved ~20s.
https://github.com/carta/automated-refactoring/runs/5221074011?check_suite_focus=true

CWS-938 cache installed dependency

---

.github/workflows/type_annotation.yml

Improvement to venv creation step:
1. add a name
2. add missing env
3. install and upgrade: pip setuptools wheel

CWS-938 add a name and move env to venv step

---

.github/workflows/type_annotation.yml

1. avoid using docker container to run faster, speed up job run by 40 secs.
2. fix a typo of mypy_report.txt
Tested in
https://github.com/carta/automated-refactoring/pull/211 https://github.com/carta/automated-refactoring/runs/5239576758
https://github.com/carta/carta-web/pull/73970 https://github.com/carta/carta-web/runs/5239836716

CWS-938 avoid using docker container to run faster

---

.github/workflows/type_annotation.yml

Allow the client codebase to do extra setup before running Mypy.
Verified with 
https://github.com/carta/compensation-service/runs/5278064788
and 
https://github.com/carta/automated-refactoring/runs/5278094072

CWS-938 add optional setup_mypy config

---

.github/workflows/type_annotation.yml

Break down checkout and install_dependency as separate jobs.
So we can use cache more effectively.
It also allows future workflows to reuse just checkout when they don't need installed dependency.
Tested with
https://github.com/carta/automated-refactoring/pull/215/files
By caching pip http and wheel files, the deps installation time was improved from 30s
https://github.com/carta/automated-refactoring/runs/5324378354
to 22s
https://github.com/carta/automated-refactoring/runs/5324401804
Tested with
https://github.com/carta/carta-web/pull/73970
The PR comments work as expected.
By caching pip http and wheel files, the deps installation time was improved from 15m 13s
https://github.com/carta/carta-web/runs/5323855727
to 7m 47s
https://github.com/carta/carta-web/runs/5324694555

CWS-938 use dependent jobs

---

.github/workflows/type_annotation.yml

Use checkout action to checkout the branch name and use github.ref_name for branch name.
Tested with https://github.com/carta/carta-web/pull/76277

CWS-946 fix head ref name issue

---

.github/workflows/type_annotation.yml

ref_name is not a branch name when it's run by pull_request event.
That causes failure https://github.com/carta/automated-refactoring/actions/runs/2091601579
This change use head_ref when it's a pull_request
https://docs.github.com/en/actions/learn-github-actions/contexts
and use ref_name when it's not.
Tested in
- https://github.com/carta/automated-refactoring/runs/5821638869
- https://github.com/carta/carta-web/runs/5821713817

CWS-946 use head_ref when it's run by pull request

---

.github/workflows/linters.yml

Skip unnecessary install_dependency job when use_python is false.
Tested in https://github.com/carta/automated-refactoring/pull/323

CWS-1101 skip install_dependency if use_python is false

---

.github/workflows/linters.yml

CLOUDSMITH_PIP_TEST env variable is needed for integrating testing test packages.

CWS-1099 add CLOUDSMITH_PIP_TEST env variable to make deps step

---

.github/workflows/linters.yml

`log` path creation was wrongly removed [here](https://github.com/carta/.github/pull/40).
This re-add the log path creation for every run

[CWS-1132] Create log path for Mypy Linter

---

.github/workflows/linters.yml

LIBCST_PARSER_TYPE=native enables LibCST to parse 3.10 code.
https://github.com/Instagram/LibCST/releases/tag/v0.4.0

CWS-1162 Fix LibCST parsing error on Python 3.10

---

.github/workflows/linters.yml

Skip fetching cache pip artifacts cache when found venv to run faster.

CWS-1161 skip fetching cache pip artifacts when found venv

---

.github/workflows/linters.yml

`mypy` linter is failing in the ds-airflow repo. `pip-tools` is missing. https://github.com/carta/ds-airflow/runs/6882229837?check_suite_focus=true
```
Successfully installed setuptools-58.0.1
[62](https://github.com/carta/ds-airflow/runs/6882229837?check_suite_focus=true#step:6:63)
+ make deps
[63](https://github.com/carta/ds-airflow/runs/6882229837?check_suite_focus=true#step:6:64)
make: pip-sync: Command not found
[64](https://github.com/carta/ds-airflow/runs/6882229837?check_suite_focus=true#step:6:65)
make: *** [Makefile:38: install] Error 127
[65](https://github.com/carta/ds-airflow/runs/6882229837?check_suite_focus=true#step:6:66)
Error: Process completed with exit code 2.
```
Install `pip-tools`

[DTA-3653] Install pip-tools in mypy linter

---

.github/workflows/linters.yml

Some custom commands executed from reusable workflows needs the private GH Token to be executed.

[CWS-1016] Add GH CI Token to run custom commands

---

.github/actions/prepare_fixit_venv.yml
.github/workflows/linters.yml
configs/.flake8
configs/mypy.ini
requirements.txt

Add support to use `flake8` as a reusable workflow.
This change on fixit-linter must be published: https://github.com/carta/automated-refactoring/pull/351
Configurations:
- Carta-Web: https://github.com/carta/carta-web/pull/78204
- Automated-Refactoring: https://github.com/carta/automated-refactoring/pull/364
- Compensation-Service: https://github.com/carta/compensation-service/pull/920
- DS-Airflow: https://github.com/carta/ds-airflow/pull/976
- LLC-UI: Don't use this workflow because it's a non-python codebase
- Financials-RPC-Server: https://github.com/carta/financials-rpc-server/pull/247

[CWS-1134] Add Flake8 to reusable workflow

---

.github/actions/prepare_fixit_venv.yml
.github/workflows/validator.yml
.yamllint

Parse errors on YAML files used by GitHub Actions are only captured during runtime. 
This workflow can analyze all `.yml` files in this codebase using the [yamllint library](https://yamllint.readthedocs.io/en/stable/index.html) to capture structural errors early in tests.
Result tests: https://github.com/carta/.github/actions/runs/2674038686

Adding YAML validator

---

.github/actions/prepare_fixit_venv.yml
.github/workflows/linters.yml
configs/.flake8
configs/mypy.ini
requirements.txt

Add support to use flake8 as a reusable workflow.
This change on fixit-linter must be published: https://github.com/carta/automated-refactoring/pull/351
Configurations:
Carta-Web: https://github.com/carta/carta-web/pull/78204
Automated-Refactoring: https://github.com/carta/automated-refactoring/pull/364
Compensation-Service: https://github.com/carta/compensation-service/pull/920
DS-Airflow: https://github.com/carta/ds-airflow/pull/976
LLC-UI: Don't use this workflow because it's a non-python codebase
Financials-RPC-Server: https://github.com/carta/financials-rpc-server/pull/247
This is a reopen after reverting this: https://github.com/carta/.github/pull/41

[CWS-1134] Configuring Flake8 as a reusable workflow

---

.github/workflows/linters.yml

Some codebases use custom validations that uses local modules. This change fix the import problem that was happening on `carta-web`.
Tested here: https://github.com/carta/carta-web/actions/runs/2707389168

Fix pep8 not found for flake8 run in carta-web

---

.github/actions/prepare_fixit_venv.yml
.github/workflows/linters.yml

Tested in https://github.com/carta/automated-refactoring/runs/7456608316?check_suite_focus=true
fixit-venv-3.8-e331759beb509154809cdd3e67835074-0.0.193--v0.1.0 is used as the cache key in prepare_fixit_venv job, run_mypy, run_flake8 and run_fixit_linters jobs.

CW-338 download fixit-requirements.txt in the beginning

---

.github/workflows/linters.yml

Some codebases does not include `mypy` as a dependency on their `requirements` file. This starts to cause `mypy not found` error in those codebases.
We previously installed `mypy` at `venv` but this was moved by this PR: https://github.com/carta/.github/pull/65
We're reverting this change.

Add a default mypy installation at venv
